#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[427] =
    {   0,
        0,    0,  115,  113,  111,  111,  113,  113,  113,   97,
       97,   97,  103,   93,   90,   94,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,  113,
      111,   92,    0,  100,    0,    0,  110,  109,  112,  105,
        0,  104,  103,    0,   95,   91,   96,   98,   98,   98,
       10,   98,   98,   98,   14,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   44,   49,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   58,   59,   98,   62,   98,   98,   98,

       98,   98,   98,   98,   98,   98,   98,   98,   79,   98,
       98,   98,   98,   98,   98,   98,   98,    0,  102,    0,
       99,  112,    0,  108,  104,    0,    0,  106,    1,    2,
        9,   11,   98,    3,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   36,   98,   98,    0,   98,   98,
       98,   98,   98,   98,   47,   98,   51,   98,   98,   98,
        5,    4,   55,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   74,   98,   98,
       98,    6,   98,   98,   98,   98,   98,   98,   98,   98,

       98,  101,    0,  107,   98,   98,   15,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   29,   98,   98,   98,   98,   98,   98,   98,   98,
       39,    0,   40,   98,   98,   98,   98,   98,   98,   48,
       50,   98,   53,   54,   56,   98,   60,   98,   98,   98,
       98,   98,   98,   98,   69,   98,   98,   98,   98,   98,
       76,   98,   98,   98,   98,   98,   83,   98,   85,   98,
       98,   88,   89,   98,   98,   98,   16,   17,   98,   98,
       98,   98,    7,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   34,   35,   98,   38,   40,   41,

       42,   98,   98,   98,   98,   98,   98,   98,   63,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       78,   80,   98,   98,   98,   98,   87,   98,   98,   98,
       98,   19,   21,   98,   22,   98,   24,   98,   98,   98,
       28,   98,   31,   32,   33,   98,   98,   43,   98,   46,
       98,   98,   98,   61,   98,   98,   98,   98,   68,   98,
       98,   72,   73,   98,   98,   81,   82,   84,   98,   98,
       13,   98,   18,   98,   23,   25,   26,   27,   98,   37,
       98,   98,   47,   98,   57,   98,   65,   98,   98,   98,
       98,   98,   77,   98,   98,   98,   20,   30,   98,   98,

       52,   98,   98,   98,   98,   71,   75,   86,   98,   15,
       98,   45,   64,   98,   67,   98,   98,   98,   66,   70,
       98,   98,   98,    8,   12,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    1,    7,    8,
        8,    8,    9,    8,   10,   11,    8,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    8,   13,
       14,   15,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,    1,   43,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[432] =
    {   0,
        0,    0,  839,  869,   69,   72,  822,   74,   75,  869,
      824,   67,   72,   71,  869,  818,   61,   61,   66,   83,
       66,  113,   61,   90,  110,   78,   89,  125,  131,  118,
      130,  117,    0,  136,  178,  141,  160,  177,  179,  109,
      209,  869,  108,  161,  825,  212,  214,  822,    0,  185,
      232,  187,  234,  238,  869,  869,  869,    0,  131,  209,
      186,  189,  204,  194,    0,  236,  210,  232,  231,  229,
      245,  230,  229,  249,  246,  236,  243,  241,  245,  274,
      268,  245,  286,    0,  262,  247,  278,  289,  286,  275,
      288,  283,  295,    0,    0,  305,  300,  333,  309,  314,

      302,  308,  310,  316,  305,  315,  316,  339,    0,  341,
      348,  348,  343,  352,  355,  341,  344,  375,  376,  785,
      439,    0,  377,  316,  368,  381,  312,  204,    0,    0,
        0,    0,  358,    0,  345,  351,  369,  361,  371,  372,
      385,  373,  391,  375,  387,  399,  401,  404,  388,  408,
      410,  394,  412,  417,  414,  406,  411,  439,  412,  417,
      411,  424,  429,  436,  440,  429,    0,  439,  430,  446,
        0,    0,    0,  440,  449,  443,  449,  458,  461,  455,
      462,  454,  457,  466,  461,  471,  473,    0,  470,  480,
      486,    0,  478,  484,  490,  478,  482,  481,  494,  501,

      499,  138,  153,  148,  498,  510,  515,  506,  516,  521,
      514,  523,  517,  507,  509,  526,  519,  522,  535,  519,
      523,    0,  538,  536,  533,  534,  549,  539,  552,  558,
        0,  551,    0,  547,  552,  556,  568,  555,  567,    0,
        0,  554,    0,    0,    0,  561,    0,  565,  563,  573,
      583,  576,  582,  580,    0,  574,  591,  581,  595,  589,
        0,  590,  601,  593,  591,  595,    0,  612,    0,  614,
      615,    0,    0,  606,  620,  623,    0,    0,  608,  609,
      611,  618,    0,  628,  623,  620,  638,  622,  630,  638,
      631,  642,  645,  632,    0,    0,  645,    0,  869,    0,

       71,  649,  658,  643,  659,  664,  661,  659,    0,  656,
      659,  666,  678,  680,  679,  685,  686,  669,  681,  687,
        0,    0,  690,  691,  678,  676,    0,  691,  687,  683,
      700,    0,    0,  687,    0,  689,    0,  698,  709,  697,
        0,  718,    0,    0,    0,  708,  720,    0,  708,    0,
      713,  726,  732,    0,  727,  715,  736,  721,    0,  730,
      742,    0,    0,  733,  743,    0,    0,    0,  744,  727,
        0,  749,    0,  750,    0,    0,    0,    0,  736,    0,
      743,  744,    0,  756,    0,  748,    0,  759,  749,  765,
      761,  755,    0,  761,  779,  763,    0,    0,  772,  771,

        0,  777,  788,  789,  793,    0,    0,    0,  779,    0,
      797,    0,    0,  783,    0,  784,  796,  805,    0,    0,
      792,  791,  798,    0,    0,  869,  856,  859,  101,  862,
      865
    } ;

static yyconst flex_int16_t yy_def[432] =
    {   0,
      426,    1,  426,  426,  426,  426,  426,  427,  428,  426,
      426,  426,  426,  426,  426,  426,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  430,
      426,  426,  427,  427,  426,  428,  428,  426,  431,  426,
      426,  426,  426,  426,  426,  426,  426,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  430,  430,  426,
      426,  431,  426,  426,  426,  426,  426,  426,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  426,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  426,  426,  426,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  426,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  426,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,    0,  426,  426,  426,  426,
      426
    } ;

static yyconst flex_int16_t yy_nxt[940] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   33,   33,
       33,   40,    4,    4,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   33,   33,   33,
       41,   41,   41,   41,   41,   41,   44,   47,   50,   45,
       64,   48,   52,   53,   55,   56,   51,   59,   66,   60,
       80,   54,   67,   81,   61,   68,   62,   63,   69,   74,

       65,   70,   71,   58,   75,   82,   72,   85,   86,   64,
       44,  119,   73,  121,  347,   51,   59,   66,   60,   80,
       54,   67,   81,   61,   68,   62,   63,   69,   74,   65,
       70,   71,   76,   75,   82,   72,   85,   86,   83,   77,
       87,   73,   78,   84,   88,   79,   90,   92,   89,   98,
       94,  120,   99,   93,   91,  100,  108,  129,   95,  204,
       96,   76,   97,   44,  204,  101,  121,   83,   77,   87,
      109,   78,   84,   88,   79,   90,   92,   89,   98,   94,
      118,   99,   93,   91,  100,  108,  129,   95,  110,   96,
      111,   97,  113,  112,  101,  102,   50,  103,  125,  109,

      114,  115,  116,  132,   51,  104,  126,  105,  117,  106,
       41,   41,   41,  107,   47,  128,   47,  110,   48,  111,
       48,  113,  112,  133,  102,  134,  103,  130,  135,  114,
      115,  116,  132,   51,  104,  126,  105,  117,  106,  138,
      123,  123,  107,  124,   52,   53,  127,  127,  131,  128,
      143,  136,  133,   54,  134,  137,  130,  135,  139,  140,
      141,  144,  145,  149,  150,  146,  151,  142,  138,  152,
      153,  147,  154,  155,  157,  158,  156,  131,  148,  143,
      136,  162,   54,  160,  137,  166,  167,  139,  140,  141,
      144,  145,  149,  150,  146,  151,  142,  161,  152,  153,

      147,  154,  155,  157,  163,  156,  168,  148,  159,  169,
      162,  170,  160,  171,  166,  167,  172,  173,  178,  164,
      165,  174,  175,  128,  176,  182,  161,  124,  185,  183,
      186,  189,  190,  163,  184,  168,  187,  159,  169,  177,
      170,  191,  171,  192,  188,  172,  173,  178,  164,  165,
      174,  175,  179,  176,  182,  193,  180,  185,  183,  186,
      189,  190,  181,  184,  194,  187,  195,  196,  177,  197,
      191,  198,  192,  188,  199,  200,  201,  119,  119,  125,
      205,  179,  206,  207,  193,  180,  208,  126,  124,  203,
      203,  181,  204,  194,  209,  195,  196,  210,  197,  211,

      198,  214,  212,  199,  200,  201,  215,  216,  217,  205,
      218,  206,  207,  219,  220,  208,  126,  202,  202,  213,
      221,  222,  223,  209,  224,  225,  210,  226,  211,  227,
      214,  212,  228,  229,  230,  215,  216,  217,  231,  218,
      158,  233,  219,  220,   43,  234,  235,  236,  213,  221,
      222,  223,  237,  224,  225,  238,  226,  241,  227,  239,
      242,  228,  229,  230,  243,  244,  245,  231,  246,  240,
      233,  247,  248,  232,  234,  235,  236,  249,  250,  253,
      254,  237,  251,  255,  238,  256,  241,  257,  239,  242,
      258,  252,  259,  243,  244,  245,  260,  246,  240,  261,

      247,  248,  232,  262,  263,  266,  249,  250,  253,  254,
      267,  251,  255,  264,  256,  265,  257,  268,  269,  258,
      252,  259,  270,  272,  273,  260,  271,  274,  261,  275,
      276,  277,  262,  263,  266,  278,  279,  280,  281,  267,
      282,  283,  264,  284,  265,  285,  268,  269,  286,  287,
      288,  270,  272,  273,  289,  271,  274,  290,  275,  276,
      277,  291,  292,  293,  278,  279,  280,  281,  294,  282,
      283,  295,  284,  296,  285,  297,  298,  286,  287,  288,
      299,  300,  301,  289,  302,  303,  290,  304,  305,  306,
      291,  292,  293,  307,  308,  309,  310,  294,  311,  312,

      295,  313,  296,  314,  297,  298,  315,  316,  317,  299,
      300,  301,  318,  302,  303,  319,  304,  305,  306,  320,
      321,  322,  307,  308,  309,  310,  323,  311,  312,  324,
      313,  325,  314,  326,  327,  315,  316,  317,  328,  329,
      330,  318,  331,  332,  319,  333,  334,  335,  320,  321,
      322,  336,  337,  338,  339,  323,  340,  341,  324,  342,
      325,  343,  326,  327,  344,  345,  346,  328,  329,  330,
      348,  331,  332,  349,  333,  334,  335,  350,  351,  352,
      336,  337,  338,  339,  353,  340,  341,  354,  342,  355,
      343,  356,  357,  344,  345,  346,  358,  359,  360,  348,

      361,  362,  349,  363,  364,  365,  350,  351,  352,  366,
      367,  368,  369,  353,  370,  371,  354,  372,  355,  373,
      356,  357,  374,  375,  376,  358,  359,  360,  377,  361,
      362,  378,  363,  364,  365,  379,  380,  381,  366,  367,
      368,  369,  382,  370,  371,  383,  372,  384,  373,  385,
      386,  374,  375,  376,  387,  388,  389,  377,  390,  391,
      378,  392,  393,  394,  379,  380,  381,  395,  396,  397,
      398,  382,  399,  400,  383,  401,  384,  402,  385,  386,
      403,  404,  405,  387,  388,  389,  406,  390,  391,  407,
      392,  393,  394,  408,  409,  410,  395,  396,  397,  398,

      411,  399,  400,  412,  401,  413,  402,  414,  415,  403,
      404,  405,  416,  417,  418,  406,  419,  420,  407,  421,
      422,  423,  408,  409,  410,  424,  425,  118,   46,  411,
       43,   57,  412,   49,  413,   42,  414,  415,  426,  426,
      426,  416,  417,  418,  426,  419,  420,  426,  421,  422,
      423,  426,  426,  426,  424,  425,   43,   43,   43,   46,
       46,   46,  118,  118,  118,  122,  426,  122,    3,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,

      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426
    } ;

static yyconst flex_int16_t yy_chk[940] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    6,    6,    6,    8,    9,   12,    8,
       18,    9,   13,   13,   14,   14,   12,   17,   19,   17,
       23,   13,   19,   23,   17,   19,   17,   17,   19,   21,

       18,   19,   20,  429,   21,   24,   20,   26,   27,   18,
       43,   40,   20,   43,  301,   12,   17,   19,   17,   23,
       13,   19,   23,   17,   19,   17,   17,   19,   21,   18,
       19,   20,   22,   21,   24,   20,   26,   27,   25,   22,
       28,   20,   22,   25,   28,   22,   29,   30,   28,   32,
       31,   40,   32,   30,   29,   34,   36,   59,   31,  204,
       31,   22,   31,   44,  203,   34,   44,   25,   22,   28,
       36,   22,   25,   28,   22,   29,   30,   28,   32,   31,
      202,   32,   30,   29,   34,   36,   59,   31,   37,   31,
       37,   31,   38,   37,   34,   35,   50,   35,   52,   36,

       38,   39,   39,   61,   50,   35,   52,   35,   39,   35,
       41,   41,   41,   35,   46,  128,   47,   37,   46,   37,
       47,   38,   37,   62,   35,   63,   35,   60,   64,   38,
       39,   39,   61,   50,   35,   52,   35,   39,   35,   67,
       51,   51,   35,   51,   53,   53,   54,   54,   60,   54,
       69,   66,   62,   53,   63,   66,   60,   64,   68,   68,
       68,   70,   71,   72,   73,   71,   74,   68,   67,   75,
       76,   71,   77,   78,   79,   80,   78,   60,   71,   69,
       66,   82,   53,   81,   66,   85,   86,   68,   68,   68,
       70,   71,   72,   73,   71,   74,   68,   81,   75,   76,

       71,   77,   78,   79,   83,   78,   87,   71,   80,   88,
       82,   89,   81,   90,   85,   86,   91,   92,   97,   83,
       83,   93,   93,  127,   96,   99,   81,  124,  101,  100,
      102,  104,  105,   83,  100,   87,  103,   80,   88,   96,
       89,  106,   90,  107,  103,   91,   92,   97,   83,   83,
       93,   93,   98,   96,   99,  108,   98,  101,  100,  102,
      104,  105,   98,  100,  110,  103,  111,  112,   96,  113,
      106,  114,  107,  103,  115,  116,  117,  118,  119,  125,
      133,   98,  135,  136,  108,   98,  137,  125,  123,  126,
      126,   98,  126,  110,  138,  111,  112,  139,  113,  140,

      114,  142,  141,  115,  116,  117,  143,  144,  144,  133,
      145,  135,  136,  145,  146,  137,  125,  118,  119,  141,
      147,  148,  149,  138,  150,  151,  139,  152,  140,  153,
      142,  141,  154,  155,  156,  143,  144,  144,  157,  145,
      158,  159,  145,  146,  121,  160,  161,  162,  141,  147,
      148,  149,  163,  150,  151,  164,  152,  166,  153,  165,
      168,  154,  155,  156,  169,  170,  174,  157,  175,  165,
      159,  176,  177,  158,  160,  161,  162,  178,  179,  181,
      182,  163,  180,  183,  164,  184,  166,  185,  165,  168,
      186,  180,  187,  169,  170,  174,  189,  175,  165,  190,

      176,  177,  158,  191,  193,  195,  178,  179,  181,  182,
      196,  180,  183,  194,  184,  194,  185,  197,  198,  186,
      180,  187,  199,  200,  201,  189,  199,  205,  190,  206,
      207,  208,  191,  193,  195,  209,  210,  211,  212,  196,
      213,  214,  194,  215,  194,  216,  197,  198,  217,  218,
      219,  199,  200,  201,  220,  199,  205,  221,  206,  207,
      208,  223,  224,  225,  209,  210,  211,  212,  226,  213,
      214,  227,  215,  228,  216,  229,  230,  217,  218,  219,
      232,  234,  235,  220,  236,  237,  221,  238,  239,  242,
      223,  224,  225,  246,  248,  249,  250,  226,  251,  252,

      227,  253,  228,  254,  229,  230,  256,  257,  258,  232,
      234,  235,  259,  236,  237,  260,  238,  239,  242,  262,
      263,  264,  246,  248,  249,  250,  265,  251,  252,  266,
      253,  268,  254,  270,  271,  256,  257,  258,  274,  275,
      276,  259,  279,  280,  260,  281,  282,  284,  262,  263,
      264,  285,  286,  287,  288,  265,  289,  290,  266,  291,
      268,  292,  270,  271,  293,  294,  297,  274,  275,  276,
      302,  279,  280,  303,  281,  282,  284,  304,  305,  306,
      285,  286,  287,  288,  307,  289,  290,  308,  291,  310,
      292,  311,  312,  293,  294,  297,  313,  314,  315,  302,

      316,  317,  303,  318,  319,  320,  304,  305,  306,  323,
      324,  325,  326,  307,  328,  329,  308,  330,  310,  331,
      311,  312,  334,  336,  338,  313,  314,  315,  339,  316,
      317,  340,  318,  319,  320,  342,  346,  347,  323,  324,
      325,  326,  349,  328,  329,  351,  330,  352,  331,  353,
      355,  334,  336,  338,  356,  357,  358,  339,  360,  361,
      340,  364,  365,  369,  342,  346,  347,  370,  372,  374,
      379,  349,  381,  382,  351,  384,  352,  386,  353,  355,
      388,  389,  390,  356,  357,  358,  391,  360,  361,  392,
      364,  365,  369,  394,  395,  396,  370,  372,  374,  379,

      399,  381,  382,  400,  384,  402,  386,  403,  404,  388,
      389,  390,  405,  409,  411,  391,  414,  416,  392,  417,
      418,  421,  394,  395,  396,  422,  423,  120,   48,  399,
       45,   16,  400,   11,  402,    7,  403,  404,    3,    0,
        0,  405,  409,  411,    0,  414,  416,    0,  417,  418,
      421,    0,    0,    0,  422,  423,  427,  427,  427,  428,
      428,  428,  430,  430,  430,  431,    0,  431,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,

      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[115] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "sql.l"
#line 2 "sql.l"
#include <stdio.h>
#include <string.h>
#include "querycsv.h"
#include "sql.h"

	/* macro to save the text and return a token */
#define TOK(name) { return name; }
#define LEX_WORKAROUND strReplace("]]", "]", yytext)
#define YY_NO_UNISTD_H 1
#line 816 "lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

int yyget_column  (yyscan_t yyscanner );

void yyset_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 17 "sql.l"


	/* literal keyword tokens */

#line 1058 "lexer.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 427 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 426 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "sql.l"
TOK(ALL)
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "sql.l"
TOK(AND)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "sql.l"
{ yylval->intval = GRP_AVG;return AMMSC; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "sql.l"
{ yylval->intval = GRP_MIN;return AMMSC; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "sql.l"
{ yylval->intval = GRP_MAX;return AMMSC; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 26 "sql.l"
{ yylval->intval = GRP_SUM;return AMMSC; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "sql.l"
{ yylval->intval = GRP_COUNT;return AMMSC; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "sql.l"
{ yylval->intval = GRP_CONCAT;return AMMSC; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "sql.l"
TOK(ANY)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 30 "sql.l"
TOK(AS)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 31 "sql.l"
TOK(ASC)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 32 "sql.l"
TOK(AUTHORIZATION)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "sql.l"
TOK(BETWEEN)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "sql.l"
TOK(BY)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "sql.l"
TOK(CHARACTER)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "sql.l"
TOK(CHECK)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "sql.l"
TOK(CLOSE)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "sql.l"
TOK(COLLATE)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "sql.l"
TOK(COMMIT)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "sql.l"
TOK(CONTINUE)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 41 "sql.l"
TOK(CONCAT)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 42 "sql.l"
TOK(CREATE)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "sql.l"
TOK(CURRENT)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "sql.l"
TOK(CURSOR)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "sql.l"
TOK(DECIMAL)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "sql.l"
TOK(DECLARE)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "sql.l"
TOK(DEFAULT)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "sql.l"
TOK(DELETE)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "sql.l"
TOK(DESC)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "sql.l"
TOK(DISTINCT)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "sql.l"
TOK(DOUBLE)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "sql.l"
TOK(ESCAPE)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "sql.l"
TOK(EXISTS)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "sql.l"
TOK(FETCH)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "sql.l"
TOK(FLOAT)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "sql.l"
TOK(FOR)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "sql.l"
TOK(FOREIGN)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "sql.l"
TOK(FOUND)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "sql.l"
TOK(FROM)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "sql.l"
TOK(GOTO)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "sql.l"
TOK(GRANT)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "sql.l"
TOK(GROUP)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "sql.l"
TOK(HAVING)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "sql.l"
TOK(IN)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "sql.l"
TOK(INDICATOR)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "sql.l"
TOK(INSERT)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 67 "sql.l"
TOK(INTEGER)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "sql.l"
TOK(INTO)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 69 "sql.l"
TOK(IS)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 70 "sql.l"
TOK(JOIN)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "sql.l"
TOK(KEY)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "sql.l"
TOK(LANGUAGE)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "sql.l"
TOK(LEFT)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "sql.l"
TOK(LIKE)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "sql.l"
TOK(NOT)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "sql.l"
TOK(NULLX)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "sql.l"
TOK(NUMERIC)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "sql.l"
TOK(OF)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "sql.l"
TOK(ON)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 "sql.l"
TOK(OPEN)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 81 "sql.l"
TOK(OPTION)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 82 "sql.l"
TOK(OR)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 83 "sql.l"
TOK(ORDER)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 84 "sql.l"
TOK(PRECISION)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 85 "sql.l"
TOK(PRIMARY)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 86 "sql.l"
TOK(PRIVILEGES)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 87 "sql.l"
TOK(PROCEDURE)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 88 "sql.l"
TOK(PUBLIC)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 89 "sql.l"
TOK(REAL)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 90 "sql.l"
TOK(REFERENCES)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 91 "sql.l"
TOK(ROLLBACK)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 92 "sql.l"
TOK(SCHEMA)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 93 "sql.l"
TOK(SELECT)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 94 "sql.l"
TOK(SET)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 95 "sql.l"
TOK(SMALLINT)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 96 "sql.l"
TOK(SOME)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 97 "sql.l"
TOK(SQLCODE)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 98 "sql.l"
TOK(TABLE)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 99 "sql.l"
TOK(TO)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 100 "sql.l"
TOK(UNION)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 101 "sql.l"
TOK(UNIQUE)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 102 "sql.l"
TOK(UPDATE)
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 103 "sql.l"
TOK(USER)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 104 "sql.l"
TOK(VALUES)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 105 "sql.l"
TOK(VIEW)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 106 "sql.l"
TOK(WHENEVER)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 107 "sql.l"
TOK(WHERE)
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 108 "sql.l"
TOK(WITH)
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 109 "sql.l"
TOK(WORK)
	YY_BREAK
/* punctuation */
case 90:
YY_RULE_SETUP
#line 113 "sql.l"
{ yylval->intval = 0;return COMPARISON; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 114 "sql.l"
{ yylval->intval = 1;return COMPARISON; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 115 "sql.l"
{ yylval->intval = 1;return COMPARISON; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 116 "sql.l"
{ yylval->intval = 2;return COMPARISON; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 117 "sql.l"
{ yylval->intval = 3;return COMPARISON; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 118 "sql.l"
{ yylval->intval = 4;return COMPARISON; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 119 "sql.l"
{ yylval->intval = 5;return COMPARISON; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 121 "sql.l"
TOK(yytext[0])
	YY_BREAK
/* names */
case 98:
YY_RULE_SETUP
#line 125 "sql.l"
{
    yylval->strval = NULL;
    snprintf_d(&(yylval->strval), "_%s", yytext);
    return NAME;
}
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 131 "sql.l"
{
    yytext[0] = '_';
    yytext[strlen(yytext)-1] = '\0';
    yylval->strval = strReplace("\"\"", "\"", yytext);
    return NAME;
}
	YY_BREAK
case 100:
/* rule 100 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 138 "sql.l"
{	yyerror2(yylineno, yytext); }
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 140 "sql.l"
{
    yytext[0] = '_';
    yytext[strlen(yytext)-1] = '\0';
    yylval->strval = LEX_WORKAROUND;
    return NAME;
}
	YY_BREAK
case 102:
/* rule 102 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 147 "sql.l"
{	yyerror2(yylineno, yytext); }
	YY_BREAK
/* numbers */
case 103:
YY_RULE_SETUP
#line 152 "sql.l"
{
    /*
    yylval->intval = atol(yytext);
    return INTNUM;
    */
    yylval->strval = strdup(yytext);
    return STRING;
}
	YY_BREAK
case 104:
#line 162 "sql.l"
case 105:
#line 163 "sql.l"
case 106:
#line 164 "sql.l"
case 107:
#line 165 "sql.l"
case 108:
YY_RULE_SETUP
#line 165 "sql.l"
{
    /*
    yylval->floatval = strtod(yytext, NULL);
    return APPROXNUM;
    */
    yylval->strval = strdup(yytext);
    return STRING;
}
	YY_BREAK
/* strings */
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 176 "sql.l"
{
		yytext[strlen(yytext)-1] = '\0';
    yylval->strval = strReplace("''", "'", yytext+1);
    return STRING;
}
	YY_BREAK
case 110:
/* rule 110 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 182 "sql.l"
{	yyerror2(yylineno, yytext); }
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 184 "sql.l"
/* white space */
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 186 "sql.l"
/* comment */
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 189 "sql.l"
/* random non-SQL text. trigger a syntax error */
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 190 "sql.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1761 "lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 427 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 427 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 426);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 190 "sql.l"



void yyerror2(long lineno, char *text) {
  fprintf(stderr, TDB_LEX_UNTERMINATED);
}

int yyerror(const char *msg) {
    fprintf(stderr, msg);
    return 1;
}

