hash3.csv: swaps.csv UnicodeData.csv
	../querycsv gethash3-a.qry
	../querycsv gethash3-b.qry
	../querycsv gethash3-c.qry
	../querycsv gethash3-d.qry
	../querycsv gethash3-e.qry
	../querycsv gethash3-f.qry

clean:
	rm results*.csv hash3.csv
