.8086
		PUBLIC	__PRO
		PUBLIC	__EPI
		EXTRN	_big_code_:BYTE
		EXTRN	__STK:BYTE
DGROUP		GROUP	CONST,CONST2,_DATA
; File contains no line numbers.
bounce_TEXT		SEGMENT	BYTE PUBLIC USE16 'CODE'
		ASSUME CS:bounce_TEXT, DS:DGROUP, SS:DGROUP
__PRO:
__EPI:
	retf
bounce_TEXT		ENDS
CONST		SEGMENT	WORD PUBLIC USE16 'DATA'
CONST		ENDS
CONST2		SEGMENT	WORD PUBLIC USE16 'DATA'
CONST2		ENDS
_DATA		SEGMENT	WORD PUBLIC USE16 'DATA'
_DATA		ENDS
		END
