# Makefile for !QueryCSV

COMPONENT  = QueryCSV
TARGET     = !RunImage
OBJS       = lexer sql hash1 hash2 hash3 hash4 querycsv
CINCLUDES  = -Itbox:,C:
LIBS       = ${EVENTLIB} ${TBOXLIB} ${WIMPLIB}
INSTDIR    ?= <Install$Dir>
INSTAPP_FILES = !Boot !Run ${TARGET} !Sprites !Sprites11 !Sprites22 Messages res

include CApp

C_WARNINGS = -fa

clean_all:: clean
        ${WIPE} ${INSTAPP} ${WFLAGS}

# Dynamic dependencies:
o.lexer:	c.lexer
o.sql:	c.sql
o.hash1:	c.hash1
o.hash2:	c.hash2
o.hash3:	c.hash3
o.hash4:	c.hash4
o.querycsv:	c.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.en_gb
o.querycsv:	h.gen
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.sql
o.querycsv:	h.lexer
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
o.querycsv:	h.querycsv
