;
; File generated by cc65 v 2.15
;
	.fopt		compiler,"cc65 v 2.15"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.import		_stdout
	.import		_stderr
	.import		_fclose
	.import		_feof
	.import		_fflush
	.import		_fgetc
	.import		_fopen
	.import		_fprintf
	.import		_fputs
	.import		_sprintf
	.import		_ungetc
	.import		_vsnprintf
	.import		_vsprintf
	.import		_malloc
	.import		_calloc
	.import		_realloc
	.import		_free
	.import		_exit
	.import		_getenv
	.import		_putenv
	.import		_strcat
	.import		_strcmp
	.import		_strcpy
	.import		_strlen
	.import		_strncat
	.import		_strstr
	.import		_memcpy
	.import		_setlocale
	.import		_gmtime
	.import		_localtime
	.import		_strftime
	.import		_time
	.import		__ctof
	.import		__fdiv
	.import		__fmul
	.import		__fadd
	.import		__fsub
	.import		__fneg
	.import		__ftostr
	.import		__fcmp
	.import		_strtod
	.import		_in_word_set
	.import		_normaliseAndGet
	.import		_isCombiningChar
	.import		_isInHash2
	.import		_yyparse
	.import		_yylex_init
	.import		_yylex_destroy
	.import		_yyset_in


l001a = $085A
l0059 = $085A
l0066 = $085A
l008c = $085A
l009f = $085A
l00ae = $085A
l011e = $0A81
l01e8 = $0A9B
l01f7 = $09D8
l0219 = $09D8
l0267 = $0A8E
l041e = $0AA7
l0421 = $0A92
l0427 = $0A9E
l042c = $0AA4
l0432 = $09A3
l0439 = $0859
l0443 = $0A86
l04af = $085A
l04c9 = $0A7A
l04cd = $0A5F
l04d1 = $0AA1
l04d5 = $0968
l04d9 = $0A4A
l04e2 = $08C7
l065a = $0AA9
l0738 = $0A68
l0934 = $0986
l09c6 = $09D8
l09d5 = $08F8
l0b15 = $09D8
l0b26 = $0A47
l0b48 = $0946
l0b51 = $0A3F
l0b56 = $0946
l0b62 = $0A47
l0b67 = $0946
l0bee = $09F2
l0bf8 = $085A
l0c97 = $0A47
l0ccc = $0946
l0d32 = $09D8
l0d3d = $08F8
l0d4d = $0A8A
l0da4 = $085A
l0e30 = $0AA7
l0e33 = $0A92
l0e5e = $0A95
l0e6a = $0A98
l0e74 = $0A99
l0e76 = $0A98
l0e7a = $0A99
l0e81 = $0A99
l0f4c = $0A2E
l0f57 = $09BE
l0f5c = $0A1C
l0f6b = $0A09
l0f85 = $0A95
l0f88 = $0A95
l102b = $0A81
l1034 = $0A81
l10e9 = $0AAB
l10ef = $09D8
l1126 = $0892
l112e = $0822
l1135 = $085B
l113c = $0A9E
l113f = $0859
l117a = $0AAB
l1180 = $09D8
l1194 = $0892
l119c = $0822
l11a3 = $085B
l1209 = $0A55
l1282 = $0A71
l12d2 = $0A9B
l12eb = $0A9B
l146a = $0A47
l1472 = $0A47
l147c = $0920
